# Generated by Django 5.0.1 on 2024-01-21 23:17

import communifyapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communifyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=communifyapp.models.content_file_name),
        ),
    ]
