# Generated by Django 5.0.1 on 2024-01-19 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communifyapp', '0002_post_image_post_private_post_text_alter_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
