# Generated by Django 5.0.1 on 2024-01-22 00:02

import communifyapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communifyapp', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to=communifyapp.models.content_file_name),
        ),
    ]
