# Generated by Django 5.0.1 on 2024-01-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communifyapp', '0003_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttype',
            name='type_name',
            field=models.CharField(choices=[('social', 'Social'), ('political', 'Political'), ('Economic', 'Economic'), ('other', 'Other')], max_length=255),
        ),
    ]
