# Generated by Django 5.0.1 on 2024-01-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communifyapp', '0003_remove_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
    ]
