# Generated by Django 5.0.1 on 2024-01-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communifyapp', '0004_alter_posttype_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('social', 'Social'), ('political', 'Political'), ('Economic', 'Economic'), ('other', 'Other')], max_length=255),
        ),
        migrations.DeleteModel(
            name='PostType',
        ),
    ]
