# Generated by Django 5.0.1 on 2024-01-23 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communifyapp', '0004_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_Likes',
            new_name='Like',
        ),
    ]
