# Generated by Django 5.0.1 on 2024-01-27 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communifyapp', '0006_share'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='user',
            new_name='from_user',
        ),
    ]
