# Generated by Django 5.0.1 on 2024-01-28 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communifyapp', '0007_rename_user_share_from_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='from_user',
            new_name='user',
        ),
    ]
